In [92]:
# Aula 03/04/2024

In [3]:
# Variavel inteira
a = 1 
print('Valor de a = '+str(a))
type(a)

Valor de a = 1


int

In [4]:
# Variave dupla precisão
b = 1.0
print(b)
type(b)

1.0


float

In [5]:
# Converter float para int
c = int(b)
print(c)
type(c)

1


int

In [6]:
#delacrando nan
import numpy as np
d = np.nan
print(d)
type(d)

nan


float

In [7]:
# Operaçao con NaN
e = d*1
print(e)
e = d+1
print(e)
e = np.nansum([d,1])
print(e)

nan
nan
1.0


In [9]:
# Declaração de variavel texto
g = 'Giovanna'
m = "Martins"
print(g)
print(m)
print(g+m)
print(g+' '+m)

Giovanna
Martins
GiovannaMartins
Giovanna Martins


In [10]:
a == 1

True

In [11]:
h = (a==1)
print(h)
type(h)

True


bool

In [12]:
h = (a==2)
print(h)
type(h)

False


bool

In [14]:
i = True
type(i)

bool

In [15]:
ii = 'True'
type(ii)

str

In [16]:
# Operaçao ==
a==b

True

In [17]:
# Operaçao ><
a>b

False

In [18]:
# Operaçao !=
a!=b

False

In [19]:
# Operaçao >= ou <=
a>=b

True

In [20]:
# Soma
a+b

2.0

In [21]:
# Soma e atribui valor
ab = a+b
print(ab)

2.0


In [26]:
# Multiplicaçao
li = a*b # Nao use L como variável
print("Não use l como nome de variável")
j = a*b
print(j)

Não use l como nome de variável
1.0


In [27]:
# Divisao
a/b

1.0

In [28]:
# Potencia
5**2

25

In [29]:
# Operaçoes matematicas com a biblioteca math
import math
math.exp(10)

22026.465794806718

In [30]:
math.exp(0)

1.0

In [31]:
math.exp(a)

2.718281828459045

In [32]:
math.exp(-10)

4.5399929762484854e-05

In [34]:
import math as mt
mt.log(c)

0.0

In [35]:
mt.log10(100)

2.0

In [36]:
## Listas

In [39]:
myfirstlist = [1,2,3]
print(myfirstlist)

[1, 2, 3]


In [40]:
# acessando valores da lista pelo index
print(myfirstlist[0])
print(myfirstlist[2])

1
3


In [41]:
myfirstlist==a

False

In [42]:
myfirstlist[0]==a

True

In [43]:
myseclist = [1,a,'c']
print(myseclist)

[1, 1, 'c']


In [44]:
type(myseclist)

list

In [46]:
type(myseclist[2])

str

In [47]:
type(myseclist[1])

int

In [48]:
## caminhos = path

In [60]:
path = r"C:\Users\Giovanna\Desktop\24.1\Pol. ATm"
print(path)

C:\Users\Giovanna\Desktop\24.1\Pol. ATm


In [61]:
import os
# listas arquivos na pasta
os.listdir(path)

['Notas aulas Poluicao.txt', 'Passo a passo', 'Polui-ao01']

In [62]:
path = r"C:\Users\Giovanna\Desktop\24.1\Pol. ATm\Polui-ao01"
print(path)

C:\Users\Giovanna\Desktop\24.1\Pol. ATm\Polui-ao01


In [63]:
import os
os.listdir(path)

['.git',
 '.gitignore',
 'Aula01.ipynb',
 'ENS5173-2024_GiovannaMartins',
 'imputs',
 'README.md',
 'Scripts',
 'venv']

In [64]:
# selecionar primeiro arquivo listado
os.listdir(path)[0]

'.git'

In [65]:
# Concatenando caminhos 
path+"/"+os.listdir(path)[0]

'C:\\Users\\Giovanna\\Desktop\\24.1\\Pol. ATm\\Polui-ao01/.git'

In [66]:
# listando caminho concatenado
os.listdir(path+"/"+os.listdir(path)[0])

['COMMIT_EDITMSG',
 'config',
 'description',
 'FETCH_HEAD',
 'HEAD',
 'hooks',
 'index',
 'info',
 'logs',
 'objects',
 'packed-refs',
 'refs']

In [67]:
# diretorio que estou trabalhando 
os.getcwd()

'C:\\Users\\Giovanna\\Desktop\\24.1\\Pol. ATm\\Polui-ao01\\ENS5173-2024_GiovannaMartins\\venv\\Scripts'

In [71]:
# mudo de diretorio para o caminho
os.chdir('C:\\Users\Giovanna\Desktop\\24.1')

In [72]:
os.getcwd()

'C:\\Users\\Giovanna\\Desktop\\24.1'

In [75]:
# Criando direetorio
new_path = os.getcwd()+'/test'

if os.path.isdir(new_path):
    print('diretorio ja existe')
else: 
    print('Criando diretorio'+new_path)
    os.mkdir(new_path)

diretorio ja existe


In [78]:
# Criando diretorio
new_path = os.getcwd()+'/test2'

if os.path.isdir(new_path):
    print('diretorio ja existe')
    # criando um arquivo texto
    with open(new_path+"/copy.txt", "w") as file:
        file.write("Your text goes here")
else: 
    print('Criando diretorio'+new_path)
    os.mkdir(new_path)
    with open(new_path+"/copy.txt", "w") as file:
        file.write("Your text goes here")

Criando diretorioC:\Users\Giovanna\Desktop\24.1/test2


In [79]:
## Numpy arrays e Pandas dataframes

In [80]:
import numpy as np
# criando uma variavel numpy
n = np.array(0)
type(n)

numpy.ndarray

In [81]:
# criando uma variavel numpy a partir de uma lista
mythirdlist=[1,2,3,10,20,55]
n = np.array(mythirdlist)
print(n)

[ 1  2  3 10 20 55]


In [83]:
# criando uma matriz de 10x10 de numeros aleatorios de 0 e 1
n = np.random.rand(10,10)
print(n)
# dimensoes da matrix
print(n.shape)

[[0.90238839 0.82312059 0.10508614 0.60684847 0.05786522 0.00913127
  0.84752109 0.27712998 0.81160745 0.09971359]
 [0.42954482 0.66173699 0.68197844 0.73798064 0.91001241 0.64333999
  0.07257396 0.58610294 0.57389128 0.25023837]
 [0.99292488 0.45916758 0.94876493 0.98592464 0.79210952 0.67321167
  0.00747343 0.02421425 0.23176053 0.38861604]
 [0.83460405 0.37225249 0.04379658 0.99794555 0.63749563 0.3346889
  0.37056492 0.13644027 0.57569438 0.98203547]
 [0.42896877 0.39849918 0.26348491 0.49024317 0.73493889 0.10514302
  0.30055199 0.8876593  0.7398366  0.38605423]
 [0.69054228 0.59778749 0.66716331 0.30473116 0.37073879 0.2273778
  0.25398823 0.69322665 0.77035036 0.65427343]
 [0.57073252 0.33558486 0.49518261 0.71824642 0.47450868 0.25413778
  0.59159074 0.04088719 0.02018349 0.50310254]
 [0.09369297 0.53344009 0.07969121 0.1408559  0.29588074 0.81290523
  0.36538828 0.49759003 0.31631674 0.22311761]
 [0.76505751 0.88609519 0.67847992 0.05845968 0.40690549 0.83416078
  0.82909731 0

In [84]:
# Acessando valores da matriz 
n[0,:]

array([0.90238839, 0.82312059, 0.10508614, 0.60684847, 0.05786522,
       0.00913127, 0.84752109, 0.27712998, 0.81160745, 0.09971359])

In [85]:
n[:,0]

array([0.90238839, 0.42954482, 0.99292488, 0.83460405, 0.42896877,
       0.69054228, 0.57073252, 0.09369297, 0.76505751, 0.63195023])

In [86]:
n[:,1:5]

array([[0.82312059, 0.10508614, 0.60684847, 0.05786522],
       [0.66173699, 0.68197844, 0.73798064, 0.91001241],
       [0.45916758, 0.94876493, 0.98592464, 0.79210952],
       [0.37225249, 0.04379658, 0.99794555, 0.63749563],
       [0.39849918, 0.26348491, 0.49024317, 0.73493889],
       [0.59778749, 0.66716331, 0.30473116, 0.37073879],
       [0.33558486, 0.49518261, 0.71824642, 0.47450868],
       [0.53344009, 0.07969121, 0.1408559 , 0.29588074],
       [0.88609519, 0.67847992, 0.05845968, 0.40690549],
       [0.32931446, 0.80148722, 0.77952805, 0.18941986]])

In [87]:
n[0,1:5]

array([0.82312059, 0.10508614, 0.60684847, 0.05786522])

In [88]:
n[0,-1]

0.09971359216918108

In [89]:
n[0,4:-1]

array([0.05786522, 0.00913127, 0.84752109, 0.27712998, 0.81160745])

In [90]:
n[0,4:]

array([0.05786522, 0.00913127, 0.84752109, 0.27712998, 0.81160745,
       0.09971359])

In [91]:
an = np.log(n*5)
print(an)

[[ 1.50672765  1.41478535 -0.64353698  1.10996176 -1.24020078 -3.08661285
   1.44399835  0.32616927  1.40069942 -0.69601537]
 [ 0.76440872  1.19655081  1.22668068  1.30560022  1.51514087  1.16835598
  -1.01371123  1.07517807  1.0541226   0.22409659]
 [ 1.60233765  0.83109787  1.5568437   1.59526256  1.3763823   1.21374243
  -3.2869628  -2.11137586  0.14738726  0.66427445]
 [ 1.42864006  0.621255   -1.51876165  1.60738135  1.15923006  0.51488409
   0.61671127 -0.38243042  1.05725956  1.59131006]
 [ 0.76306676  0.68938806  0.27567875  0.89658417  1.30146998 -0.64299589
   0.40730339  1.49027063  1.30811198  0.65766049]
 [ 1.23915984  1.09491795  1.2047175   0.42111257  0.61718039  0.1282956
   0.23897055  1.24303964  1.34852806  1.18520799]
 [ 1.04860329  0.5175575   0.90660924  1.27849535  0.86396255  0.23955918
   1.08449771 -1.58750056 -2.29345266  0.92247664]
 [-0.75829416  0.9810294  -0.92015802 -0.35057999  0.39163909  1.40229716
   0.6026432   0.91145914  0.4584267   0.10938165]
 